name: Deploy to gh-pages

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Output
        run: |
          mkdir ./output
          cp ./index.html ./output/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          cname: xyz-tiles-comparer.vollysolutions.com
          force_orphan: true # Only keep latest commit in gh-pages (to keep repo size down)
